# Generated by Django 4.0.2 on 2022-02-16 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_category_image_alter_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['created_at']},
        ),
    ]
